spring:
  # Datasource will be provided by Testcontainers @ServiceConnection
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  # Disable SSL configuration to prevent invalid SSL Bundle instantiation
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.ssl.SslHealthContributorAutoConfiguration

springdoc:
    api-docs:
      enabled: false

amice:
  enabled: false

supabase:
  api:
    url: https://supabase.com
    jwt-secret: super-secret-jwt-token-with-at-least-32-characters-long
    jwt-issuer: http://localhost:54321/auth/v1

exact:
  oauth:
    refresh-enabled: false

logging:
  config: classpath:logback-local.xml
  structured:
    format:
      console:
jobrunr:
  dashboard:
    enabled: false
