spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
supabase:
  api:
    url: ${SUPABASE_API_URL:}
    secret: ${SUPABASE_API_SECRET:}
    publishable: ${SUPABASE_API_PUBLISHABLE:}
    jwt-secret: ${SUPABASE_API_JWT_SECRET:}
    jwt-issuer: ${SUPABASE_API_JWT_ISSUER:}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

springdoc:
  api-docs:
    enabled: true
